version: "3.9"

networks:
  web:
    external:
      name: web
  internal:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - internal

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - web
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.parking.entrypoints=websecure
      - traefik.http.routers.parking.rule=Host(`parking.block-it.ovh`)
      - traefik.http.routers.parking.tls=true
      - traefik.http.routers.parking.tls.certresolver=lets-encrypt
      - traefik.docker.network=web
      - traefik.http.routers.parking.middlewares=chain-no-auth@file