version: "3.9"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  parkplatzbackend:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "${APP_PORT}:3000"
    volumes:
    - .:/usr/src/app