version: "3.9"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  parkplatzbackend:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 3000
    volumes:
    - .:/usr/src/app
    networks:
      - web
    labels:
      - traefik.enable=true
      - "traefik.http.routers.parking.entrypoints=websecure"
      - "traefik.http.routers.parking.rule=Host(`parken.die-wg.vodka`, `parken.block-it.ovh`)"
      - "traefik.http.routers.parking.tls=true"
      - "traefik.http.routers.parking.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.parking.loadbalancer.server.port=80"
      - "traefik.http.routers.parking.middlewares=chain-no-auth@file"